### PR TITLE
use properties, not fields

### LINKED ISSUE #59: Actually use properties, not fields
Both `getproperties` and `setproperties` are documented to relate to struct properties and not its fields.
However, the implementation is very inconsistent in fields vs properties.
Calling `fieldnames` and then `getproperties`:
https://github.com/JuliaObjects/ConstructionBase.jl/blob/2044dd59b61c701b66ab43fc4b4326573c126095/src/ConstructionBase.jl#L47-L49
Reporting `fieldnames` in the error message:
https://github.com/JuliaObjects/ConstructionBase.jl/blob/2044dd59b61c701b66ab43fc4b4326573c126095/src/ConstructionBase.jl#L91

These inconsistencies lead to confusing errors, e.g.:
```julia
julia> using ConstructionBase, StructArrays

julia> s = StructArray(a=1:5)
5-element StructArray(::UnitRange{Int64}) with eltype NamedTuple{(:a,), Tuple{Int64}}:
 (a = 1,)
 (a = 2,)
 (a = 3,)
 (a = 4,)
 (a = 5,)

julia> fieldnames(typeof(s))
(:components,)

julia> propertynames(s)
(:a,)

julia> getproperties(s)
ERROR: type NamedTuple has no field components
# ConstructionBase tries to call getproperty(s, :components) which clearly doesn't exist
```

Maybe, `getproperties`
https://github.com/JuliaObjects/ConstructionBase.jl/blob/2044dd59b61c701b66ab43fc4b4326573c126095/src/ConstructionBase.jl#L46-L53
can be replaced with
```julia
@inline function getproperties(obj)
    fnames = propertynames(obj)
    NamedTuple{fnames}(getproperty.(Ref(obj), fnames))
end
```
? It infers just fine on 1.7+.

### PR DESCRIPTION
**Pull request by aplavin**
fix #59

### CODE REVIEW

File: src/ConstructionBase.jl [hunk 1]
```diff
@@ -86,9 +82,8 @@ function validate_setproperties_result(
 end
 @noinline function validate_setproperties_result(nt_new, nt_old, obj, patch)
     O = typeof(obj)
-    P = typeof(patch)
     msg = """
-    Failed to assign properties $(fieldnames(P)) to object with fields $(fieldnames(O)).
+    Failed to assign properties $(propertynames(patch)) to object with fields $(propertynames(obj)).
```
Comment (jw3126) [inline src/ConstructionBase.jl:86]:
```suggestion
    Failed to assign properties $(propertynames(patch)) to object with propertynames $(propertynames(obj)).
```

File: src/ConstructionBase.jl [hunk 2]
```diff
@@ -43,13 +43,9 @@ end
...
 getproperties(o::NamedTuple) = o
 getproperties(o::Tuple) = o
-@generated function getproperties(obj)
-    fnames = fieldnames(obj)
-    fvals = map(fnames) do fname
-        Expr(:call, :getproperty, :obj, QuoteNode(fname))
-    end
-    fvals = Expr(:tuple, fvals...)
-    :(NamedTuple{$fnames}($fvals))
+@inline function getproperties(obj::T) where {T}
```
Comment (jw3126) [inline src/ConstructionBase.jl:46]: Did you have to do a bit of tinkering for this to infer or did it work right away?

**Comment by jw3126** [comment]
@rafaqz what do you think? Should we just drop julia < v1.7 support? The alternative would be to base `getproperties` on `fieldnames`/`propertynames` based on the julia version. Which I think is a bad idea.

File: src/ConstructionBase.jl (hunk 2 above)
Comment (jw3126) [reply src/ConstructionBase.jl:46]: Do you know if the `@inline` is important?

File: src/ConstructionBase.jl [hunk 3]
```diff
@@ -43,13 +43,25 @@ end
...
+    end
+else
+    @generated function getproperties(obj)
+        fnames = fieldnames(obj)
+        fvals = map(fnames) do fname
+            Expr(:call, :getproperty, :obj, QuoteNode(fname))
+        end
+        fvals = Expr(:tuple, fvals...)
+        quote
+            if $fnames != propertynames(obj)
```
Comment (jw3126) [inline src/ConstructionBase.jl:59]: I think `propertynames` is really slow in old julia versions. Like `300ns`. I also think `setproperties` depends on `getproperties`. So thinks like `Setfield.@set` will get unacceptably slow.

File: test/runtests.jl [hunk 4]
```diff
@@ -238,6 +238,31 @@ end
...
 end
 
+# example of a struct with different fields and properties
+struct FieldProps{NT <: NamedTuple{(:a, :b)}}
+    components::NT
+end
+
+Base.propertynames(obj::FieldProps) = (:a, :b)
+Base.getproperty(obj::FieldProps, name::Symbol) = getproperty(getfield(obj, :components), name)
+ConstructionBase.constructorof(::Type{<:FieldProps}) = (a, b) -> FieldProps((a=a, b=b))
```
Comment (jw3126) [inline test/runtests.jl:248]:
```suggestion
function ConstructionBase.setproperties(obj::FieldProps, patch::NamedTuple)
    old_props = getproperties(obj)
    new_props = setproperties(old_props, patch)
    FieldProps(new_props)
end
```
This is a bit of an awkward point. The specification is that `setproperties` and `getproperties` match and that `constructorof` and `getfield.(Ref(obj), fieldnames(obj))` match. 
So this overload of `constructorof` is a bit of a hack.

File: src/ConstructionBase.jl [hunk 5]
```diff
@@ -43,13 +43,24 @@ end
...
-    fvals = map(fnames) do fname
-        Expr(:call, :getproperty, :obj, QuoteNode(fname))
+if VERSION >= v"1.7"
+    function getproperties(obj)
+        fnames = propertynames(obj)
+        NamedTuple{fnames}(getproperty.(Ref(obj), fnames))
+    end
+else
+    @generated function getproperties(obj::T) where {T}
+        if which(propertynames, Tuple{T}).sig != Tuple{typeof(propertynames), Any}
```
Comment (jw3126) [inline src/ConstructionBase.jl:53]: Interesting, technically only pure functions are allowed in `@generated`. But this might be ok in practice?

File: test/runtests.jl (hunk 4 above)
Comment (jw3126) [reply test/runtests.jl:248]: Ok you are right. I could have sworn we changed that.

File: test/runtests.jl [hunk 6]
```diff
@@ -238,6 +238,31 @@ end
...
+            (@test_throws "Failed to assign properties (:c,) to object with properties (:a, :b)" setproperties(x, c=0)) :
+            (@test_throws ArgumentError setproperties(x, c=0))
+    else
+        @test_throws ErrorException getproperties(x)
+        @test_throws ErrorException setproperties(x, a="aaa")
+        @test_throws ErrorException setproperties(x, c=0)
+    end
+end
+
+
```
Comment (jw3126) [inline test/runtests.jl:265]: Can you check if this breaks some downsteam packages on some julia versions? Something hacky like
```suggestion
using Pkg;
for p in ["Setfield", "Flatten", "ModelParameters"]
    Pkg.add(p); Pkg.test(p); Pkg.rm(p)
end
```

**Comment by rafaqz** [comment]
Julia v1.6 is LTS and this package has ~ 500 dependants.

It worries me a lot dropping 1.6 support.

**Review by jw3126 — APPROVED** [review]
LGTM (the downstream package tests hack needs to be removed before merge)

File: src/ConstructionBase.jl [hunk 7]
```diff
@@ -24,32 +24,38 @@ for (name, path) in [
     end
 end
 
-@generated function constructorof(::Type{T}) where T
```
[the remark this answers is not in the document]
Comment (rafaqz) [reply src/ConstructionBase.jl:27]: `@inferred` is not enough really if we are dropping generated functions. 

We also need benchmarks showing zero allocations.

**Comment by rafaqz** [comment]
@aplavin this is what I'm worried about

> Well, the same function works, but slower

It has to be a compile time operation on 1.6

File: src/ConstructionBase.jl (hunk 7 above)
[the remark this answers is not in the document]
Comment (jw3126) [reply src/ConstructionBase.jl]: Yes very pragmatic approach!

**Comment by jw3126** [comment]
I would like to merge this? Any objections?

File: src/ConstructionBase.jl [hunk 8]
```diff
@@ -43,13 +43,31 @@ end
...
+    end
+else
+    @generated function getproperties(obj)
+        if which(propertynames, Tuple{obj}).sig != Tuple{typeof(propertynames), Any}
+            # custom propertynames defined for this type
+            return quote
+                msg = """
+                Different fieldnames and propertynames are only supported on Julia v1.7+.
+                For older julia versions, consider overloading
+                `ConstructionBase.getproperties(obj::$obj)`.
```
Comment (jw3126) [inline src/ConstructionBase.jl:59]: I think in this interpolation `obj` is the runtime value of the variable `obj`, not its type. One way to do it would be:
```julia
quote 
    T = typeof(obj)
    msg = "... $T"
    error(msg)
end
```

**Comment by jw3126** [comment]
@aplavin can you merge master into this so the integration tests run with this PR? After they pass I will merge this PR!

**Comment by jw3126** [comment]
Thanks again @aplavin this PR is a huge improvement!

**Comment by ancapdev** [comment]
Just pulled this in to some code that now breaks.

While this solves the issue for anyone who wants to operate on custom properties, the scope of usability seems rather narrow as it breaks any type that has computed properties (trying to to call a constructor will all those properties as arguments) which you'd never want to set nor construct from.

**Comment by jw3126** [comment]
@ancapdev thanks a lot this is valuable feedback for us. Is some of that code open source, I would like to take a look at it?

**Comment by ancapdev** [comment]
@aplavin Thanks, that's a good option, we could define `getproperties` directly. Our use case is indirect through `Setfield.jl`.

@jw3126 The affected code we have is not public, unfortunately, but it's nothing particularly complex. We simply had some structs with a few computed properties, and we were using `Setfield.@set` to update underlying fields on some of these objects.

**Comment by jw3126** [comment]
If you are only interested in `Setfield.@set` I would directly overload `ConstructionBase.setproperties` and not touch `getproperties`.

**Comment by ancapdev** [comment]
That also makes sense, thanks
