### PR TITLE
WIP add constructors for base array wrappers

### LINKED ISSUE #34: Constructors for common base types?
Tim Besard just made the point

```julia
julia> Flatten.modify(CuArray, view(rand(2,2),:,:), Array)
ERROR: MethodError: no method matching SubArray(::CuArray{Float64,2}, ::Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}}, ::Int64, ::Int64)
```
And of course

```julia
using Setfield
sa = view(zeros(10, 10), :, :)
julia> @set sa.offset1 = 2
ERROR: MethodError: no method matching SubArray(::Array{Float64,2}, ::Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}}, ::Int64, ::Int64)
```

Should we add some constructors for common base wrapper types like `SubArray`?

### PR DESCRIPTION
**Pull request by rafaqz**
Some `constructorof` methods for  Base and LinearAlgebra array wrappers, as discussed in #34.

Probably we shouldn't add a constructor for `Tridiagonal` because of the undef field - seems it would break Accessors.jl/Flatten.jl etc? 

I'm not sure what to do about it long-term, possibly a PR to base using `nothing` instead of `undef` for `du2`? How many other structs have undef fields?

Closes #34

There are probably a bunch of other base objects that need `constuctorof` methods. Feel free to list more for me to add to this PR.

### CODE REVIEW

**Review by jw3126 — COMMENTED** [review]
I think we can have this. It is a bit tough since it forces us to decide more precisely whether we want `constructorof(obj)(public_fields...)` or `constructorof(public_and_private_fields...)`.

I am not sure, what's the right decision there, but I am okay with merging this and we will see later how it plays out. 
Alternatively, we could also include a `propertyvalues` function, which by default returns all the fields, and specify
```julia
constructorof(obj)(propertyvalues(obj)...) == obj
```

**Comment by rafaqz** [comment]
I was thinking about a `propertyvalues` method as well. Then we could override it for `Tridiagonal` and the few other objects that have undef fields. I cant think of another way to support Yridiagonal.

**Comment by jw3126** [comment]
Ok lets go this path. How about a slight tweak. Instead of `propertyvalues` we could return a `NamedTuple`: 
```julia
@generated function properties(obj)
    fnames = fieldnames(obj)
    fvals = map(fnames) do fname
        Expr(:call, :getproperty, :obj, QuoteNode(fname))
    end
    fvals = Expr(:tuple, fvals...)
    :(NamedTuple{$fnames}($fvals))
end

struct S;a;b;end
s = S(1,2)
properties(s)
(a = 1, b = 2)
```
You can still splat it into a function call, like it was a tuple. 
```julia
S(properties(s)...)
S(1,2)
```
But it has nicer symmetry with `setproperties`, is easier to read etc. For me turning a struct into a NamedTuple is a task that comes up every now and then.

**Comment by rafaqz** [comment]
That looks good to me. Maybe we can call it `propertiesof` to match `constructorof`

**Comment by jw3126** [comment]
`getproperties` sounds fine.

**Comment by rafaqz** [comment]
This is updated to use the changes in the getproperties PR, and can be merged once that is rebased into master.

**Comment by rafaqz** [comment]
This is ready to  rebase.

File: test/runtests.jl [hunk 1]
```diff
@@ -71,3 +79,40 @@ end
     @test CustomSetproperties(2) === setproperties(o, a=2)
     @test CustomSetproperties(2) === setproperties(o, (a=2,))
 end
+
+@testset "Default object constructors" begin
+    A1 = zeros(5, 6)
+    A2 = ones(Float32, 5, 6)
+    @testset "SubArray" begin
+        subarray = view(A1, 1:2, 3:4)
+        fields = map(fn -> getfield(subarray, fn), fieldnames(typeof(subarray)))
```
Comment (jw3126) [inline test/runtests.jl:88]: Should this be `getproperties` instead?

Comment (rafaqz) [reply test/runtests.jl:88]: yep

Comment (rafaqz) [reply test/runtests.jl:88]: Sorry I forgot to revisit the tests after these changes. I'll use `getproperties`

**Comment by rafaqz** [comment]
Made some changes to the tests if you want to hit merge if you're happy with them. I guess we should do a minor version bump after that.
